enable_cuda: TRUE

model:
    in_channels: 3
    out_channels: 1

# Placeholder hyperparameters
training:
    num_epochs: 10
    learning_rate: 0.05
    batch_size: 1
    num_workers: 2               # for torch.utils.data.DataLoader
    resume_checkpoint: null      # should be path for checkpoint .pth file or null
    save_checkpoint_freq: 5      # freq to save checkpoint wrt to epoch count. Set to 0 if no check points needs to saved

# dataset path assume segmentation/ is cwd
dataset_loc:
    train:
        img_dir: 
        degradation_values_dir: 
    val:
        img_dir: 
        degradation_values_dir: 

    # add dataset class name maybe in future if required

# location where model train results needs to be saved
results_loc: experiment_results/